# Generated by Django 5.2.9 on 2026-01-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('usuario', 'fecha', 'hora_inicio', 'hora_fin'), name='uniq_reserva_exacta'),
        ),
    ]
