# Generated by Django 5.2.9 on 2026-01-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reserva_uniq_reserva_exacta'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='uniq_reserva_exacta',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='hora_fin',
            new_name='hora_entrada',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='hora_inicio',
            new_name='hora_salida',
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('usuario', 'fecha', 'hora_entrada', 'hora_salida'), name='uniq_reserva_exacta'),
        ),
    ]
