# Generated by Django 5.2.9 on 2026-01-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_reserva_uniq_reserva_exacta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
