# Generated by Django 5.2.9 on 2026-01-21 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_reserva_checkin_reserva_checkout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='reserva',
            name='uniq_reserva_exacta',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='creado_en',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora_salida',
        ),
        migrations.AddField(
            model_name='reserva',
            name='check_out',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['check_in', 'check_out'], name='app_reserva_check_i_e62b2e_idx'),
        ),
    ]
